function CTA0296statistics = import_xcat_stats(filename, dataLines)
%IMPORTFILE Import data from a text file
%  xcat_statistics = import_xcat_stats(filename) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  xcat_statistics = import_xcat_stats(filename, dataLines) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  CTA0296statistics = importfile("C:\Users\User\Downloads\XCAT_breast_phantom_demo_20170607\XCAT_breast_phantom_demo_20170607\CTA0296\phantom_uncompressed\CTA0296_statistics.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2025 16:12:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["SegmentationClasses", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "SegmentationClasses", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "SegmentationClasses", "EmptyFieldRule", "auto");

% Import the data
CTA0296statistics = readtable(filename, opts);

end