classdef AnalyticalSphere3D < AnalyticalEllipsoid3D
    % AnalyticalSphere3D
    %   Convenience wrapper around AnalyticalEllipsoid3D with equal axes. The
    %   radius may be fixed, provided in a struct, or generated by a function
    %   handle returning such a struct for time-varying spheres.

    methods
        function obj = AnalyticalSphere3D(shapeParameters, intensity, center, rollPitchYaw)
            if nargin < 4 || isempty(rollPitchYaw)
                rollPitchYaw = [0 0 0];
            end
            if nargin < 3 || isempty(center)
                center = [0 0 0];
            end
            if nargin < 2 || isempty(intensity)
                intensity = 1;
            end
            if nargin < 1 || isempty(shapeParameters)
                shapeParameters = struct('radius_mm', 1);
            end

            obj@AnalyticalEllipsoid3D([], intensity, center, rollPitchYaw);
            obj.setShapeParameters(obj.radiusStructToAxes(shapeParameters));
            
        end

        function setShapeParameters(obj, shapeParameters)
            if isa(shapeParameters, 'function_handle')
                radiusFunction = shapeParameters;
                axesFunction = @(varargin) obj.radiusFunctionToAxes(radiusFunction, varargin{:});
                obj.setShapeParameters@AnalyticalShape3D(axesFunction);
                return;
            end

            if ~isstruct(shapeParameters)
                shapeParameters = struct('radius_mm', shapeParameters);
            end

            axesStruct = obj.radiusStructToAxes(shapeParameters);
            obj.setShapeParameters@AnalyticalShape3D(axesStruct);
        end

        function params = getShapeParameters(obj, varargin)
            axesParams = obj.getShapeParameters@AnalyticalShape3D(varargin{:});
            params = struct('radius_mm', axesParams.a_mm);
        end
    end

    methods (Access = protected)
        function params = radiusFunctionToAxes(~, radiusFunction, varargin)
            radiusValues = radiusFunction(varargin{:});
            if isstruct(radiusValues) && isfield(radiusValues, 'radius_mm')
                radiusValues = radiusValues.radius_mm;
            end
            params = struct('a_mm', radiusValues, 'b_mm', radiusValues, 'c_mm', radiusValues);
        end

        function params = radiusStructToAxes(~, radiusStruct)
            if isfield(radiusStruct, 'radius_mm')
                radiusValues = radiusStruct.radius_mm;
            elseif all(isfield(radiusStruct, {'a_mm', 'b_mm', 'c_mm'}))
                radiusValues = radiusStruct.a_mm;
            else
                error('AnalyticalSphere3D:ShapeParameters:MissingRadius', ...
                    'Sphere shape expects radius_mm or matching ellipsoid fields.');
            end

            params = struct('a_mm', radiusValues, 'b_mm', radiusValues, 'c_mm', radiusValues);
        end
    end
end
