classdef AnalyticalSphere3D < AnalyticalEllipsoid3D
    % AnalyticalSphere3D
    %   Convenience wrapper around AnalyticalEllipsoid3D with equal axes. The
    %   radius may be fixed, provided in a struct, or generated by a function
    %   handle returning such a struct for time-varying spheres.
    %
    %   Shape parameters (struct fields):
    %     radius_mm  - Sphere radius (diameter = 2 * radius_mm).
    %     a_mm       - Optional ellipsoid semi-axis along BODY x-axis (full width = 2 * a_mm).
    %     b_mm       - Optional ellipsoid semi-axis along BODY y-axis (full width = 2 * b_mm).
    %     c_mm       - Optional ellipsoid semi-axis along BODY z-axis (full width = 2 * c_mm).
    %     pose       - Optional pose struct (see AnalyticalShape3D).

    methods
        function obj = AnalyticalSphere3D(intensity, shapeParameters)
            if nargin < 2 || isempty(shapeParameters)
                shapeParameters = struct('radius_mm', 1);
            end
            if nargin < 1 || isempty(intensity)
                intensity = 1;
            end

            shapeParameters = AnalyticalSphere3D.normalizeSphereParameters(shapeParameters);
            obj@AnalyticalEllipsoid3D(intensity, shapeParameters);
        end
    end

    methods (Static, Access = private)
        function params = normalizeSphereParameters(shapeParameters)
            if isa(shapeParameters, 'function_handle')
                params = @(varargin) AnalyticalSphere3D.radiusToAxes(shapeParameters(varargin{:}));
            else
                params = AnalyticalSphere3D.radiusToAxes(shapeParameters);
            end
        end

        function params = radiusToAxes(radiusInput)
            if isa(radiusInput, 'function_handle')
                radiusInput = radiusInput();
            end

            if isstruct(radiusInput)
                pose = [];
                if isfield(radiusInput, 'pose')
                    pose = radiusInput.pose;
                    radiusInput = rmfield(radiusInput, 'pose');
                end

                if isfield(radiusInput, 'radius_mm')
                    radiusValues = radiusInput.radius_mm;
                elseif all(isfield(radiusInput, {'a_mm', 'b_mm', 'c_mm'}))
                    if ~(isequal(radiusInput.a_mm, radiusInput.b_mm) && isequal(radiusInput.a_mm, radiusInput.c_mm))
                        error('AnalyticalSphere3D:ShapeParameters:AxesMustMatch', ...
                            'Sphere parameters must have equal a_mm, b_mm, and c_mm values.');
                    end
                    radiusValues = radiusInput.a_mm;
                elseif isempty(radiusInput)
                    radiusValues = 1;
                else
                    error('AnalyticalSphere3D:ShapeParameters:MissingRadius', ...
                        'Sphere shape expects radius_mm or matching ellipsoid fields.');
                end

                params = struct('a_mm', radiusValues, 'b_mm', radiusValues, 'c_mm', radiusValues);
                if ~isempty(pose)
                    params.pose = pose;
                end
            else
                validateattributes(radiusInput, {'numeric'}, {'real', 'nonnegative', 'finite'});
                params = struct('a_mm', radiusInput, 'b_mm', radiusInput, 'c_mm', radiusInput);
            end
        end
    end
end
