classdef AnalyticalSphere3D < AnalyticalEllipsoid3D
    % AnalyticalSphere3D
    %   Convenience wrapper around AnalyticalEllipsoid3D with equal axes. The
    %   radius may be fixed, provided in a struct, or generated by a function
    %   handle returning such a struct for time-varying spheres.

    methods
        function obj = AnalyticalSphere3D(shapeParameters, intensity, center, rollPitchYaw)
            if nargin < 4 || isempty(rollPitchYaw)
                rollPitchYaw = [0 0 0];
            end
            if nargin < 3 || isempty(center)
                center = [0 0 0];
            end
            if nargin < 2 || isempty(intensity)
                intensity = 1;
            end
            if nargin < 1 || isempty(shapeParameters)
                shapeParameters = struct('radius_mm', 1);
            end

            obj@AnalyticalEllipsoid3D(shapeParameters, intensity, center, rollPitchYaw);
        end
    end

    methods (Access = protected)
        function params = validateParameters(obj, params)
            % validateParameters  Accept radius-based parameters and map to axes.
            %   Supports numeric radii, structs with radius_mm, or ellipsoid
            %   axis structs with equal components.

            if isa(params, 'function_handle')
                params = params();
            end

            if ~isstruct(params)
                validateattributes(params, {'numeric'}, {'real', 'nonnegative'});
                params = struct('radius_mm', params);
            end

            if isfield(params, 'radius_mm')
                ellipsoidParams = obj.radiusStructToAxes(params);
            elseif all(isfield(params, {'a_mm', 'b_mm', 'c_mm'}))
                if ~(isequal(params.a_mm, params.b_mm) && isequal(params.a_mm, params.c_mm))
                    error('AnalyticalSphere3D:ShapeParameters:AxesMustMatch', ...
                        'Sphere parameters must have equal a_mm, b_mm, and c_mm values.');
                end
                ellipsoidParams = params;
            else
                error('AnalyticalSphere3D:ShapeParameters:MissingRadius', ...
                    'Sphere shape expects radius_mm or matching ellipsoid fields.');
            end

            params = obj.validateParameters@AnalyticalEllipsoid3D(ellipsoidParams);
        end
        
        function params = getAxesParameters(obj, varargin)
            if isa(obj.shapeParameters, 'function_handle')
                params = obj.radiusFunctionToAxes(obj.shapeParameters, varargin{:});
            else
                params = obj.radiusStructToAxes(obj.shapeParameters);
            end

            params = obj.validateParameters(params);
        end

        function params = radiusFunctionToAxes(~, radiusInput, varargin)
            if isa(radiusInput, 'function_handle')
                radiusValues = radiusInput(varargin{:});
            else
                radiusValues = radiusInput;
            end

            if isstruct(radiusValues)
                if isfield(radiusValues, 'radius_mm')
                    radiusValues = radiusValues.radius_mm;
                elseif all(isfield(radiusValues, {'a_mm', 'b_mm', 'c_mm'}))
                    radiusValues = radiusValues.a_mm;
                else
                    error('AnalyticalSphere3D:ShapeParameters:MissingRadius', ...
                        'Sphere shape expects radius_mm or matching ellipsoid fields.');
                end
            end

            params = struct('a_mm', radiusValues, 'b_mm', radiusValues, 'c_mm', radiusValues);
        end

        function params = radiusStructToAxes(~, radiusStruct)
            if isfield(radiusStruct, 'radius_mm')
                radiusValues = radiusStruct.radius_mm;
            elseif all(isfield(radiusStruct, {'a_mm', 'b_mm', 'c_mm'}))
                radiusValues = radiusStruct.a_mm;
            else
                error('AnalyticalSphere3D:ShapeParameters:MissingRadius', ...
                    'Sphere shape expects radius_mm or matching ellipsoid fields.');
            end

            params = struct('a_mm', radiusValues, 'b_mm', radiusValues, 'c_mm', radiusValues);
        end
    end
end
