% demo_lung_waveform.m
% Demo of the time-varying lung ellipsoid waveform using the current
% lung_ellipsoid_waveform interface.
%
% The lung waveform helper returns the shared lung radius and height used
% by the simplified model. This demo reconstructs the left and right lung
% visualization structs and then uses visualize_lung_motion to show the
% geometry and waveform over time.

clear; clc; close all;

%% 1) Time axis
T_total_s = 40;
N = 4001;
t_s = linspace(0, T_total_s, N);

%% 2) Breathing pattern
f_bpm = 12 * ones(size(t_s));
VT_L = 0.5 * ones(size(t_s));
Vres_L = 1.2 * ones(size(t_s));
Vbase_L = 2.4 * ones(size(t_s));
bellyFrac = 0.6 * ones(size(t_s));
inspFrac = (1/3) * ones(size(t_s));
lungSeparation_mm = 5 * ones(size(t_s));

lungParameters = struct( ...
    'f_bpm', f_bpm, ...
    'VT_L', VT_L, ...
    'Vres_L', Vres_L, ...
    'Vbase_L', Vbase_L, ...
    'bellyFrac', bellyFrac, ...
    'inspFrac', inspFrac, ...
    'lungSeparation_mm', lungSeparation_mm);

%% 3) Run the waveform model and build visualization structs
[lungRadius_mm, lungHeight_mm] = lung_ellipsoid_waveform(t_s, lungParameters);
lungPosition_mm = lungRadius_mm + lungSeparation_mm;
modeledLungVolume_L = (4/3) * pi .* lungRadius_mm.^2 .* lungHeight_mm / 1e6;

fprintf('Demo modeled tidal volume = %.3f L (baseline = %.3f L)\n', ...
    max(modeledLungVolume_L) - min(modeledLungVolume_L), modeledLungVolume_L(1));

leftEllipsoidParams = struct( ...
    'a_mm', lungRadius_mm, ...
    'b_mm', lungRadius_mm, ...
    'c_mm', lungHeight_mm, ...
    'R_mm', lungRadius_mm, ...
    'H_mm', lungHeight_mm, ...
    'lungPosition_mm', lungPosition_mm, ...
    'pose', struct( ...
        'center', struct( ...
            'x_mm', -lungPosition_mm(:), ...
            'y_mm', zeros(numel(lungPosition_mm), 1), ...
            'z_mm', zeros(numel(lungPosition_mm), 1)), ...
        'roll_deg', 0, ...
        'pitch_deg', 0, ...
        'yaw_deg', 0));

rightEllipsoidParams = struct( ...
    'a_mm', lungRadius_mm, ...
    'b_mm', lungRadius_mm, ...
    'c_mm', lungHeight_mm, ...
    'R_mm', lungRadius_mm, ...
    'H_mm', lungHeight_mm, ...
    'lungPosition_mm', lungPosition_mm, ...
    'pose', struct( ...
        'center', struct( ...
            'x_mm', lungPosition_mm(:), ...
            'y_mm', zeros(numel(lungPosition_mm), 1), ...
            'z_mm', zeros(numel(lungPosition_mm), 1)), ...
        'roll_deg', 0, ...
        'pitch_deg', 0, ...
        'yaw_deg', 0));

%% 4) Visualize waveform and ellipsoid geometry over time
visOpts = struct();
visOpts.frameStep = 4;
visOpts.nTheta = 200;

visualize_lung_motion(t_s, leftEllipsoidParams, rightEllipsoidParams, visOpts);
